const ICONS = {
  html: "icons/html-5.svg",
  css: "icons/css-3_official.svg",
  sass: "icons/sass.svg",
  js: "icons/javascript.svg",
  jquery: 'icons/jquery-icon.svg',
  php: 'icons/php-alt.svg',
  mysql: "icons/mysql.svg",
  android: "icons/android-icon.svg",
  typescript: "icons/typescript-icon.svg",
  vue: "icons/vue.svg",
  node: "",
  angular: "icons/angular-icon.svg",
  react: "",
  wordpress: "icons/wordpress-icon.svg",
  figma: "icons/figma.svg",
  github: "icons/github-icon.svg",
};

const ICONLABELS = {
  html: "HTML5",
  css: "CSS",
  sass: "SASS",
  js: "JavaScript Vanilla",
  jquery: "jQuery",
  php: "PHP",
  mysql: "MySQL",
  android: "Android UI",
  typescript: "TypeScript",
  vue: "Vue JS",
  node: "Node JS",
  angular: "Angular JS",
  react: "React JS",
  wordpress: "WordPress",
  figma: "Figma",
  github: "Git",
};